export enum TablePoemFields {
	Id = 'id',
	PoemName = 'poemName',
	AuthorId = 'authorId',
	Grad = 'grad',
	UrlParam = 'urlParam',
	VideoProvider = 'videoProvider',
	VideoEmbedId = 'videoEmbedId',
	VideoActor = 'videoActor',
	VideoSocialYoutube = 'videoSocialYoutube',
	VideoSocialInst = 'videoSocialInst',
	VideoSocialVk = 'videoSocialVk',
	VideoSocialTelegram = 'videoSocialTelegram',
	VideoSocialTiktok = 'videoSocialTiktok',
	VideoAudio = 'videoAudio',
	ExplanationText = 'explanationText',
	PoemText = 'poemText',
}
